[build]
  command = "npm run build"
  publish = "dist"
  # Explicitly set the build environment
  environment = { NODE_VERSION = "18", PYTHON_VERSION = "off", MISE_PYTHON_INSTALL = "false", MISE_AUTO_INSTALL = "false" }

# No Go configuration or detection should happen

# Set redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Set caching headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 