[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Explicitly disable Go
[build.environment.GO_VERSION]
  enabled = false

# Set redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Set caching headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 